import 'package:equatable/equatable.dart';

/// Type of a football notification alert.
enum NotificationAlertType {
  goal,
  kickoff,
  halfTime,
  fullTime,
  result,
  prediction,
  breakingNews,
  transferNews;

  /// Human-readable label for the alert type.
  String get label {
    switch (this) {
      case NotificationAlertType.goal:
        return 'Goal';
      case NotificationAlertType.kickoff:
        return 'Kickoff';
      case NotificationAlertType.halfTime:
        return 'Half Time';
      case NotificationAlertType.fullTime:
        return 'Full Time';
      case NotificationAlertType.result:
        return 'Result';
      case NotificationAlertType.prediction:
        return 'Prediction';
      case NotificationAlertType.breakingNews:
        return 'Breaking News';
      case NotificationAlertType.transferNews:
        return 'Transfer News';
    }
  }
}

/// A single notification alert generated by the app (either from a live
/// match event or a news/prediction feed).
class NotificationAlertEntity extends Equatable {
  const NotificationAlertEntity({
    required this.id,
    required this.type,
    required this.title,
    required this.body,
    required this.createdAt,
    this.matchId,
    this.payload,
  });

  final String id;
  final NotificationAlertType type;
  final String title;
  final String body;
  final DateTime createdAt;
  final int? matchId;

  /// Optional deep-link payload (e.g. "type=match&id=123").
  final Map<String, dynamic>? payload;

  NotificationAlertEntity copyWith({
    String? id,
    NotificationAlertType? type,
    String? title,
    String? body,
    DateTime? createdAt,
    int? matchId,
    Map<String, dynamic>? payload,
  }) {
    return NotificationAlertEntity(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      body: body ?? this.body,
      createdAt: createdAt ?? this.createdAt,
      matchId: matchId ?? this.matchId,
      payload: payload ?? this.payload,
    );
  }

  @override
  List<Object?> get props =>
      [id, type, title, body, createdAt, matchId, payload];
}
